name: 'chat'
version: 0.0.1
description: A sample realtime Dart chat app.
author: Matteo Rosati <mrosati@h-art.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  test: '^0.12.13'
  mockito: '^0.11.0'

transformers:
- dart_to_js_script_rewriter
- test/pub_serve:
    $include: test/**_test.dart